#+TITLE: Boat

* Boat

#+begin_quote
Meditation techniques are useful, they let us learn by doing. Too many
techniques, or complicated steps and sequences however are confusing, and lead
to a sense of being lost.

Egyszerűsítsd le a lényegre. Egy lélegzet, egy BUD-DHO. Belégzésre ismételd
magadban a mantra felét, BUD-, középen a megállás, kilégzésre, -DHO. BUD-DHO.
Kész vagy.

A lényeg a béke, a lényeg a megértés, ami megállít.

A béke abból ered, hogy az érzékek visszahúzódnak és befelé néznek. A keresés
megáll, mert ami van elég, és sehova nem kell menni. Az öröm abból fakad, hogy
az elme megérti, hogy nincs boldogság amit a világban hajszolni lehet. Az
értékek átrendeződnek.

Hol van a béke most? Hol van a megértés most? Semmit nem kell megoldani.
BUD-DHO, tíz lélegzet, és vége a világnak. Elég, ha a kérdés megállítja az
elmét. Ez a megállás a csend, a válasz pedig nem szükséges.

Hétköznapi helyzetben, egyszerűsítsd le, amíg mindig felismerhető. Teljesen
fáradt vagy, semmi energiád, kavarog az agyad a napi jövés-menéstől, de a légzés
akkor is elérhető, a csend ott is érezhető.
#+end_quote

- bail out the boat
- things are empty
- bailing out the boat
- not heavy with self

#+begin_quote
One of the teaching images of the Buddha is bailing out the boat. Imagine when
a boat or ship is full of water, or full of goods it has to carry, then the
boat moves slowly. It is burdened, heavy and slow, all the water and things are
weighing it down.

We would like our boat to go fast, don't we? But at the same time we are holding
onto everything that is in it. We have to lighten the boat, give up the self
which is the heavy burden. We create ’me’ and ’mine’, we create ’what I have to
be’, ’what I should be’, ’what I am’. This is what is holding to boat down, this
is the weight.

Emptiness is when the boat is empty. It moves swiftly, because it is light as a
feather, not heavy with self, the story and drama of ’me’ and ’mine’.
#+end_quote

- happy, here
- afraid to open

#+begin_quote
Often just stopping to look is enough to notice that we are happy where we are.
Stop and stay with it. A lot of us think we are never happy.

But when we are suffering, we know that there is something to learn, something
to understand, the attachment is hiding somewhere.

Letting go is not always cutting off. Sometimes we are telling ourselves to let
go, because we are afraid to open or commit ourselves, and depriving ourselves
pleases our self-critical mind. This ill-will and anger toward ourselves is
self-destructive.

See through the trick, the judgement that 'this is not ultimately
transcendental', which stops you from doing something good, how is that
wholesome?

Sometimes letting go means to let go of the fear to pull out all the stops and
do your best. Not because it is useful, not because somebody expects it, but
because you know it is the right thing to do, and you love doing what you do.
#+end_quote

- map story

#+begin_quote
One time I was walking in the countryside, and I had sheets of paper maps with
me. I had been walking for a few days, and I usually make notes on the map,
track which paths I followed, where did I find a good camping spot, where did I
receive alms-food in the village and so on, it is a kind of log or journal. When
I get back to the monastery, I scan the maps and type up the notes.

This was a rainy and windy day, and I was walking in the middle of nowhere on
the muddy roads. I sat down to rest, and I thought, 'let's mark up this last
section of the route on the map.' I kept the map sheets in a plastic folder. I
take a look, and I can see today's map, but yesterday's map is not there. /I've
lost yesterday's map./ With all the notes.

I must have dropped it sometime earlier when pulling out today's map for a look.
It could be kilometers behind me, in the mud somewhere, or the wind must have
blown it into some corner. /I've lost yesterday's map./ I felt so shaken, it was
comically absurd. I couldn't remember the last time I was so disappointed.

The Sun was going to set soon, and I still had a lot of distance to walk. The
next morning I had to reach the next town, otherwise I can't go alms-round and I
don't eat that day. (The monk's rules don't allow us to store food from one day
to the next.)

So I couldn't easily turn around and start tracing my way back. I was sitting
there, thinking, 'I should let go. It's just some notes. This is just a state of
mind, a good monk should let go.'

But all that didn't sit right. I thought, 'What am I afraid of here? Why is it
wrong to like that piece of paper? Why is it OK to be critical, but not OK to
like myself? I love doing what I do, and I'm going back for my map.'

I found it about 500m behind me. It was floating in a puddle, soaked, but
intact. I lifted it like it was an archaeological artefact.

I rolled it up in a towel and it dried eventually. It was twilight by the time I
found a place to camp but everything was well. Next day I did get to the town in
time for alms-round, a man and two ladies offered me food for the day.
#+end_quote

