#+TITLE: Bones

 - restore view; life, the whole of it; a baby and the ash urn are same weight

* Bones (1311w)

:TOPICS:
- the bones as the fixed parts
- at the core
- kindness and acceptance
:END:

#+begin_quote
The bones are fascinating because they show the core, the fixed part of the body
that determines what it is, what it can and cannot do.

It is also frightening because seeing bones reminds us of the suffering of
losing what we know, but they also teach us what we don't know -- how to not
create that suffering with kindness and acceptance, and this is where the
meditation on bones open a way.

No matter what we think of the surface, the bones give us a message from beyond
our thinking, that there is no ideal state about that surface.
#+end_quote

:TOPICS:
- standing posture
- head balance
:END:

#+begin_quote
Meditating in the standing posture, it is easy to feel the the bones of the
body.

In standing, you have to put in a bit more effort to maintain the posture. Sway
the body a bit and feel the weight. Develop that sense that there is something
you have to hold. Relax the knees and let them bend a bit. Don’t lock them
straight, that stresses the joints and your posture becomes rigid.

Feel out the balance and notice there is a body which you are holding up. There
is a pressure on the ground, gravity is pulling it down. Let the hands down on
the side if that is comfortable, or collect them in front of the abdoment if
that feels better.

Watch the posture. Notice how you are standing. Take a deep breath, watch how
the bones move. This is the mechanics of breathing. Is there something limiting
it? Notice if you are standing straight, or if the shoulders are hunched,
perhaps tired. Watch the balance of the head, find the position where the head
sits on top of the spine by its own weight. Pulling in the chin gently, and the
crown of the head pushing the sky.

The head controls the shape of the spine to a great degree. Because of sitting
on chairs, we fall into a habit of carrying the head in a manner pushed forward.
This creates a tension in the back muscles. Experiment, what does it feel like,
to pull the head back a bit. The muscles in the back relax.
#+end_quote

:TOPICS:
- bones
- body made of pieces
:END:

#+begin_quote
Feel how the bones connect. There is this perception of an inner structure which
supports the body from the inside. Rigid pieces, stacked on top of each other.
There is a sensation in the legs, a rigid perception, which are the long leg
bones. There is pressure. The hip bone is resting on top of the legs, the torso
moves joined on to it. The ribcage expands and contracts with the breathing. The
spine is holding the weight in a curve. The head is sitting on top of the spine.
The skull bones are streching the skin on the face.

It is made out of pieces. Pieces that in some places hard and rigid, and some
places soft and flexible, these give it shape. There is hair on top of the head.
Some hair on the hands and other parts.

The habitual perception of the body, of our body and of other people's body, is
that we see it as one unit, as one thing. Trom that perspective develops an
obsession that it has some ideal way to be. That it has to be a certain shape,
height, different qualities.

These are wordly judgements, perceptions which our society drill into us.
Advertisements and media messages reinforce these expectations and we believe in
them, but when we look closer we see this is a twisted perception, not according
to reality.

These social expectations create an anxiety about our appearance, we are
concerned about what other people think about our body, and we create opinions
about their bodies.
#+end_quote

:TOPICS:
- hair and nails dropping on the ground
:END:

#+begin_quote
We can watch how this anxiety is conditioned when parts of the body are
separated. We can be concerned about our hair for example, but only when it is
on our head. When it is cut off, we are not anxious about a pile of hair on the
ground. Similarly, when cutting our nails, what is that point when it is no
longer 'me' and 'mine'?

When we contemplate it this way, as something made up of pieces, we can see the
body is not one unit, it is made of pieces and parts which have their own
nature, and behave according to that, not concerned with our opinions or others.
Bones, skin, hair, teeth and nails, they are the way they are. Contemplating
this gives us confidence in accepting them with kindness.

The body is a blessing. This meditation is not to develop aversion or negative
emotions toward the body. Health is a blessing, it supports us in everything we
do. The Buddha called health the greatest treasure.
#+end_quote

:TOPICS:
- bodily awareness stops anger
:END:

#+begin_quote
Breathing in, breathing out, attention is turned inwards, noticing 'there is a
body'. The mind is not seeking anything, not going out somewhere. From the feet,
to the legs, abdomen, chest, arms, the skull and the head, you can feel the skin
as it is streched against the bone of the skull.
  
Watching the body like this is like watching the rain, there is nothing to do,
nothing to decide, and rain goes on without us having to get involved.

A testi tudatosság megállítja a haragot, neheztelést és belső vádaskodást.
Gondolatokon keresztül nincs a haragból kiút, de ezt ilyenkor nem látjuk.
Valahogy fontosnak érezzük, hogy mérgesek legyünk, pedig csak az idő telik el
vele fájdalmasan. Erre vágyunk, hogy vége legyen és nyugodtan mehessenek a
dolgok tovább.
#+end_quote

:TOPICS:
- no stories
- stories in an old book
- interpreting somebody else's dream
- time-travelling back to the present
- resolution starts
:END:

#+begin_quote
Megfigyeljük a test részeit, és látjuk, hogy nem hordoznak semmilyen sztorit.
Így fellélegezhetünk, hogy nem vagyunk a sztorikhoz láncolva, azokat mi hozzuk
létre.

Ehhez a figyelemhez mindig vissza tudunk térni, egy belégzés és kilégzés elég
ahhoz, hogy emlékezzünk a keletekzésre és elmúlására, és a problémáink olyanná
válnak, mint a sztorik egy régi újságban. Ráununk kibogozni a szálakat, mintha
valaki más álmait kellene értelmeznünk. Ami a valóság, az mindig itt van a jelen
tapasztalatunkban. Nem az válik fontossá, hogy mi a sztori, hanem az, hogy
tudjunk arra figyelni, amikor itt vagyunk.

A testi tudatosság enged a kívánságokból és rávezet arra, hogy szerencsések
vagyunk, hogy itt lehetünk.

Hova akarunk jutni? Elkezdhetjük most. Ha nehéz dologról van szó, szinte biztos,
hogy nem tudjuk mit kell tenni, de elképzelhetjük magunkat, hogy pár év múlva
visszanézünk a mostra, és megköszönjük magunknak, hogy elkezdtük eloszlatni a
ködöt.

A jövőbeli önmagunk szemével visszanézünk a jelenre, és megkérdezzük, itt
akarunk lenni? Meglepő módon a válasz gyakran nem a helyzetet boncolgatja, hanem
hálás azért, hogy ilyen szerencsések vagyunk, hogy itt lehetünk ahol vagyunk.
Van amit meg akarunk még tenni, de már azt is meg tudjuk köszönni, amit eddig
megtapasztalhattunk.

We don't stop often enough to notice when we are happy and peaceful. When the
mind is clear and calm, it is naturally grateful for what is here, it is able to
say 'thank you' for the blessings we received in our life. The present is good,
and whatever way it develops for the rest of our life, we are able say 'thank
you'.

Az elhatározás, hogy figyelni fogunk, megteremti ennek a kellő feltételt. Nem erő
vagy képesség kérdése, ezek helyhez és időhöz kötöttek. Az elhatározás, a befelé
irányuló flismerő figyelem nem egy adott körülményhez kötött. Az eredménye a
helyes szemlélet, amiben látjuk a dolgok megfelelő helyét, és mit kell azokkal
tenni -- vagy amikor nincs más teendő, csak megállni, figyelni és lélegezni.
#+end_quote

