#+TITLE: But How

* But How

sit shorter more often than longer but rarely or never

the point is to integrate awareness into everyday life

sit 10 minutes, stay with the silence and watch the breathing. the rest you can figure out as it happens.

the first few 10min sessions will be about learning what kind of things happen in 10mins. after that you will have questions

take experience as the ground truth, instead of trying to reproduce what the
book says. Connect words and experience by starting with the expereience.

don't stay in the grayness
movement gives wisdom, gray stillness doesn't know anything

chances are there will be more going on in the inner world than you asked for
this is part of the plan. observe that change.
stay with the commitment, self-respect.
trust the boredom and the containment. the mind gets really creative when it has only a little to work with.
how long, 40-60
before everyone wakes up
closing the door during lunch
sit or stand or walk. be creative to find the windows. waiting for the bus, commuting, unless you are dirving. 

learning from action

techniques, briefly

- BUD-DHO
- space b/w thoughts
- counting
