#+TITLE: Cycles

* Cycles (1072w)

:TOPICS:
- more technique, what to do, how to do more
- steps and techniques
- not linear, cycles
- these cycles ignore our ideas about progress
- not a meditation carreer
- the harder we push the more pain we are in
- knowledge doesn't become yours
:END:

A meditációs utasítások lépésekben épülnek fel, de nem ezek a lépések a
meditáció célja. Viszont kialakul bennünk az a benyomás, hogy lépésről lépésre
kell valamit teljesítenünk.

A lépések az imitációs tanulás részei. Mint amikor kézbe veszünk egy új tárgyat,
követjük az utasításokat és kipróbáljuk a használatát, megismerik annak
lényegét. Ezután viszont a lépésekre már nincs szükségük a lényeg
alkalmazásához.

A meditációt is így ismerjük meg. A 'miért'-je nem világos a gondolati
megismerés számára, és hiába olvasunk válaszokat erre a kérdésre, a dolog nem
válik tisztábbá, csak még több véleménnyel lesz tele a fejünk.

A meditáció ezt az érzésen, tapasztaláson keresztüli megismerést tanítja.

It would be great if our meditation would develop in a linear way. We imagine
that we are going to sit down, perhaps a bit unfocused, and after an hour, /if
we are good meditators/, we are going to feel stillness and our mind is going to
be clear and focused.

Later, when we recollect how the meditation went, we observe that this is not
what happens. Our experience doesn't develop in a linear way from shallow to
deep, or from distracted to focused. We think this is our fault, because we are
not good meditators, or we are not doing the steps right.

As soon as we try to follow steps, everything is different from our
expectations. So maybe we are not trying hard enough? We keep pushing and it
only gets more painful. This is the feeling of trying to fit an opinion onto the
experience.

The mind develops in cycles, and these cycles ignore our goals to develop a
meditation career.

Take experience as ground truth and start from there. What is the experience? We
can watch how attention moves as an activity. It progresses through cycles
rather than linearly. First the mind is content to sit and attention becomes
clear and still, then thoughts start coming up and we follow them, then we stop
and stay content with the stillness again, thinking might even stop without us
noticing that we are not thinking, and then attention starts moving and we
notice ourselves thinking again. Memories, desire, restlessness can come up and
we notice we have work to do so we deal with them, then the mind is again
content and returns to stay with the stillness.

Some knowledge is necessary, but a little is enough. Remembering the teachings
of the Budda is a treasure which doesn't run out. But this knowledge doesn't
become ours, and we can't save it. Whatever we learn, every time we start again
from the begnning, and trust the present knowing from there.

:TOPICS:
- distinctions
- consciousness stops naming
- knowing the mind
:END:

The mind would like to say that it is a good meditation, or a bad meditation. It
wants to create a distinction and name it. This preference creates
dissatisfaction, and we try to improve our experience. We decide how our
experience should be, and strive towards creating a state. There is an image, a
concept, a named distinction which we decided and from our current state of not
being like that, we want to change our state and become like that. This is the
dissatisfied mind. It wants to become something, it wants to arrive at a state
and have a name.

This would continue, this seeking for a distinction, this seeking for a name,
this seeking for a state, this would continue until we notice that it is
happening.

When it becomes visible in consciousness, that we are doing this, then it stops.
It stops because ignorance, not seeing, was replaced with seeing. Seeing is
enough to stop that compulsion from continuing.

This is enough, knowing the mind this way we arrive at a sense of gratitude for
being. Not a gratitude for anything in particular, just that there is
experience, there is knowing, there is clarity, and the freedom which allows us
to stop going towards more and more, or a different thing.

:TOPICS:
- feelings with no edged
- stopping the naming process
- symbols of thought are limited
- knowing without naming
:END:

#+begin_quote
In a balanced posture the feelings of the body are easy to observe. We turn
attention inwards, in a curious manner, wanting to discover.

These feelings are often not clear. We experience them but they don’t have clear
boundaries. They don’t have an edge, or a definite shape. When we try to find
names for it, we struggle, we are not sure what to call it.

All the symbols which could be names are inadequate. In our culture we are
trained to trust knowledge, and we like to go back to that security with names
and terminology. We are not familiar with the cognition that doesn't use names
and symbols. The feelings, the experience itself is not clearly defined, just
the fact that we know that there is this experience.

Seeing it this way we can distinguish the naming process. The experience of the
body is rather amorphous, it doesn’t have edges. Breathing in, the experience is
everywhere at once. Breathing out, the experience is everywhere at once. The
whole body is breathing and there is feeling and expereience, but there are no
clear names.

The symbols constructed by the mind can only go so far. This is not our fault,
every symbol constructed comes with its own limit. Dedication to finding them
and trying to identify what kind of consciousness is this, is a limited effort.
It is bound by the limits of categories.

We see this limitation and we rather stop doing it. We will rather enjoy staying
with the knowing which includes experience without filtering. Dropping the
naming process, we recognize we can simply know these feelings. We can know that
there is experience, without having to find a name for it. This is on a
different level than the symbols themselves, then the words and concepts.

Sitting still, breathing in, breathing out. It becomes easy to recognize the
mental states. Recognize the feeling that comes with unwholesome mental states.
A sense of heat, restlessness, dissatisfaction and anxiety.

We know that there has to be patience, there has to be endurance with that
state. It will cease, it will change. We can wait for it. When we know where we
are, then we don’t have to do much more. Conditions in the mind will change on
their own. If we are not putting more fuel on it, the fire will burn up and cool
down on its own.

The result will be a wholesome mind which understands. Not being compelled, not
being forced, we recognize it by the coolness and comfort of being free.
#+end_quote

:TOPICS:
- closing
- After teaching, Sariputta abides in emptiness.
- After teaching, the Buddha returns to concentration on the signless.
- They continue to meditate.
:END:
