#+TITLE: Elements

* Elements (1102w)

:TOPICS:
- the elements don't have 'me' and 'mine'
- superimposed
- consciousness without the 'me'
- the frame of experience
:END:

#+begin_quote
We experience the body sitting, and we tend to think ’I am sitting’, ’This is
something which I am doing’. But the experience, what is it?

It is made of the fundamental areas of experience, such as the pressure, the
feeling of hard pieces of the body connecting to each other, maintaining the
shape of the body. There is a sense of hot and cold. The heat of the floor, cold
on the exposed skin, the cold of the air as is comes in, sense of warmth when
the air goes out. Rigid bones moving, the ribcage expands and contracts. The
solid parts. The heated parts. The moving parts. The flexibility. These make up
the experience of the body.

Observing the material part of our experience this way removes ’us’ from the
picture. We are not creating the solid, the heat. The body does these things on
its own. We are not creating the air, the movement or the flexibility. We
experience them but it would be hard to say that we are responsible for creating
them. They appear because they are the nature of the body, and they disappear
when the body changes.

We take credit for it after the fact, and perceive 'me' and 'mine' in this.
But where were 'we' involved in their arising? Can we stop their ceasing in any way?

These are parts of experience, but when seeing the arising and ceasing, it
doesn't appear to us that this is ’me’ or 'mine'. It becomes apparent that that
perception is superimposed, something we stamp onto it when not paying attention.

This material experience, the solids, the heat, movement, flexibility, this is
within a space. There is direction around us, forward, backward, up and down.
There is space, as another fundamental area of expereience.

And there is a perceiving consciousness, because we are not statues. Statues
would also sit here, like a pile of stones or sand sculptures, but the statue
doesn’t have an experience of what it’s like to be a statue. We have this
quality which is about what it is like to sit here. This is different from the
material properties of the matter, and different from space. It is another
fundamental of our experience. This creates the environment, the whole scenery
which we call the world, or life. This is the frame in which it happens.
#+end_quote

:TOPICS:
- creation and destruction of elements
- we're not doing it, just recognizing it
- taking credit for it when not aware
:END:

#+begin_quote
We see our expereiences to change. There is creation, some of them are
happening to us, there is destruction, some of them are ceasing, some pressure
appears, some pain dissapears. We become conscious of some experience, some idea
pops into our head and disappears. The body changes, even within half an hour of
sitting. The body doesn’t feel the same way at the beginning of the meditation
than at the end. Pressure and tension accumulates, muscles get tired and sore.

In this we create ourselves. Especially when we are hurt, even a small cut on
the finger, immediately the expereience is definetly 'me' and certainly 'mine'.
These preferences initiate the ’me’ being born.

The solidity is not concerned with this. The pressure, flexibility, the space
and consciousness, are not concerned with being something, being ’me’ or being
’mine’. We know what these things are, but it is something we put onto the
fundamentals. This is the birth and death which we create. Recognizing it is
sufficient.
#+end_quote

:TOPICS:
- standing up from the game
- freedom from the rules of 'me' and 'mine'
- fearlessness, not holding on to what we can lose
- free to stand up and walk away
:END:

#+begin_quote
It is like recognizing that there is a game. We didn’t know that there was a
game, but once we understand, we can stop following the rules, the compulsive
tendencies, ’you must do this, you must do that’, and there is a freedom from
the game.

We stop playing the game that ’I have to be this, I have to be that’. We go back
to watching the body, experiencing knowing with awareness, and the sense of
freedom that we are not compelled one way or another. There are things which we
will do, there are choices which we will make, but there is not going to be a
hurry or rush, because we understand the properties of the environment. We
understand the properties of the wider sphere that is around us.

Fear also drops with that knowing. When ’me’ and ’mine’ is something
constructed, it is no longer the most important thing, and our priorities
reorganize themselves. We can recognize it, but also know we don’t have to be
afraid when things will change in a way we didn’t want.

And they do change don't they? While we are not looking, something we really
like changes, and now we lost it, it is only a memory in the past.

This is the game of the ego, the game of ’me’ and ’mine’. When we are not aware
of it, we are elevated when winning, and miserable when losing.

We are not going to build our life on elevated states of emotion, we have more
understanding than that. We go into long-term relationships and carry
responsibilities for our community knowing that it will be hard work, but
satisfying and worthwhile to have done something good.

Nonetheless, 'me' and 'mine' gives us a heartache. We can feel broken and sick
when something dear changes. Usually we don't prepare, and we think the pain is
just part of the package. Tragedy is sad by its nature, but we also think we
should be in pain and suffer. That is the game we don't have to play, but we see
very few examples of such excellence.
#+end_quote

:TOPICS:
- acting on it consciously
- move freely, not driven by dissatisfaction
- greater space, we are a small part
:END:

#+begin_quote
Be conscious, be grateful for having the life that we have. We can give up the
craving, give up the dissatisfaction. This way we know that the teaching is
something we can use.

We are relieved to find ourselves in a wider space than before. Letting go is
the freedom which the heart recognizes and wants to return to. To greater space
where there is space for ’me’, space for ’mine’, but it is only a small part of
the picture now.
#+end_quote
