#+TITLE: Heroes

- beliefs produce thoughts, thoughts are stories, stories have heroes, hero of the story you didn't create
- think better thoughts
- good thoughts, what stops you
- the unknown is fear
- have the worst happened yet
- the wise think the thought they want to think
- who are your heroes? reflects your highest values

* Heroes

Thoughts don't have a good reputation in meditation handbooks. They are seen as
obstructions, some kind of fault, something annoying and unwanted like flies. We
come away with the impression that good meditators don't think, and if we are
thinking a lot, we can't be good.

Certainly, the distracted mind and obsessive thinking is a painful expereience,
but what about wholesome thoughts? Courage, resolution, kindness and gratitude
all express themselves in spontaneous thought.

Thoughts are embedded in a story, and the story is a description of the way we
see the world. Thoughts have to meet the unknown, become conscious of it and
benefit us with a wider perspective. In this way they are like heroes.

Who are the heroes whose example you respect? A person who did something
surprisingly good, and you wanted to remember and do likewise? Such as teachers,
friends, historical figures.

Perhaps somebody popular, the author of a book? Do you know what they do for a
living? What is their life story, how do they live? It can be very different
from the show in the book. If their life turns out to be virtuous and reliable,
this will strengthen our trust in their work. It it turns out to be full of
scandals and suffering, we might want to keep some distance from their ideas.

Our heroes represent our highest values. What are the thoughts which represent
our highest values?

"I am a human being who has the capacity for complete freedom from greed, hatred
and delusion."

"I have the courage and strength to be with my experience, whether that is easy
and happy, or hard and difficult. I have the space and courage to be with that,
and I am grateful for the life I have."

What is that, something unseen, which stops us from thinking that, can we expand
our view and see it? Thoughts meeting the unknown and trying to make sense of
it.

The way the psyche operates, its first response to an unknown, new phenomena is
a sense of alertness to possible danger and fear, to determine how to respond.
This is described as the orienting reflex, or 'What is it?' reflex. It may
determine in a split-second the event to be harmless, but before that there is
fear.

In meditation we turn towards the unknown, and an initial sense of confusion and
fear is the appropriate response to that.

It is often the fear, sense of danger and suffering which turns on our
alertness, and we start to meditate to solve the problem. But the meditation
doesn't solve our problems, it teaches us not to fear the problem. Our
perspective widens to include the new and unknown. We respond with courage and
skilful action, which often have to be improvised on the spot.

We can also find that courage by voluntarily meeting the unknown ahead of time,
when we are in a safe position to approach carefully.

Think of the worst possible outcome of a decision, which can be reasonable to
expect in an uncertain world, and consider it in detail. Maybe the worst is not
that bad, and anything better is only going be beneficial. There are always
sacrifices which have to be made. Early on, we are lucky to choose what to
sacrifice. Later, as life changes, it will choose the sacrifices without asking
us.

Thoughts are determined by what we believe about the world around us. They way
we see the world will determine the kind of thoughts our mind creates. Or the
reverse, we can't think or imagine something that isn't in our world view. When
that view expands, we are struck with new thoughts which are astonishing to us.

We can discover what our unconscious beliefs are by observing what kind of
thoughts and fantasies play out in the mind. They will tell us the stories which
we believe, we think them because at that moment they made sense to us. When we
reflect on the desire, anger, or some obsessive thought, it may not seem
intelligent any more, but this revision of values is the benefit of watching
them.

The thoughts are embedded in a story about the world, which only loosely
connects to the physical environment. Rather, it describes the world of possible
actions, or how to navigate and find a path in life. We are going to act out the
views and thoughts we believe in, the results can be miserable if our view was
too wacky.

It is comical what kind of thoughts and stories we can be convinced to be
correct, so save a smile or two in the side pocket for the time when we look
back on the present. At the time we feel we must be right. If our views can
change like that, how about the current one? Remembering that this is not sure
either stops us from digging ourselves into a hole.

Our thoughts and fatasies are sometimes horrible. They can be violent, full of
anger or jealousy. They are the product of the psyche, the mechanics of the
mind, they can really muddled and tangled up. This is the underworld of the
thinking mind -- chaotic, dark and destructive.

what has just flickered through your mind? as if thoughts were the measure.
horrible thoughts sometimes. you're not that.

the critic is dead, the fantasy is dead, not responding to the persent, just a product of past conditions

We can step back and observe them. Keep other people safe from them, we have the
responsibility to keep them under check with self-restraint, and with patience
they will pass.

space b/w thoughts, you are still conscios. can you watch that space?

We are not these thoughts, the hero is the conscious awareness
which recognizes that they have no possible benefit. The mind will change and
there will be better thoughts, we can wait for them.

There is a hero's journey which describes how the story of the self develops. In
the Buddha's teaching we can see how this reflects the effort of abandoning the
unwholesome and developing the wholesome.

- not heroes of our story
- there is a real story, but we didn't make it
- the body doesn't have a story

The Buddha teaches us about a truth which is greater than the stories of the
self. There is a story which is not about how the self develops, but which lets
go of the self.

When the Buddha taught groups of people, as we know from suttas, the recorded
texts, at the end there is often a summary of how did those people receive the
teaching. Were they delighted or upset, and how many of them understood it. And
there would be entire groups of people, who, after the Buddha taught, would
understand the truth at the same occasion.

In one discourse, they can’t have done a lot of studying. They can’t have all
been in the same kind of emotional state, or they can’t have had the same kind
of way of thinking. If you have fifty people in a room, they are all different,
and some of them will be really uncommon types.

Understanding of the truth is not personality development, it is seeing through
the personality as a conditioned process arising and ceasing, and not being
blocked or compelled by it. The truth is not in what we create. If we create
something, that might be beautiful and interesting, but it is going to end. The
personality is not what we trust.

let go of the person is to stay with it, not rejecting it. like with a child

When this idea comes up in the mind, that ‘This is beyond me. I can’t do this.
This is hopeless.’ Then you can remember that this is not where our refuge is.
The Buddha is the awakening, the Dhamma is the truth, the Sangha is the virtuous
community. Our refuge is in the awakening, which recognizes the truth and
practices virtue in the world. This is what we trust.

Always return to what is present experience. It is never complicated. Present
experience is always through the senses. Our world is a world of the senses.
Anything which you experience is through the body and its mental impressions.

There is touch through the body, there is vision, hearing, smelling, tasting,
and the mental experiences. There is a physical and a mental description of
everything that we experience. That is all that the world is.

We create stories throught the perception of time. We tell ourselves a story
about something or somebody who I am, who comes from yesterday, but when we look
at present expereience, the story breaks up and stops.

Watching experience in the body, it doesn’t have a story. The body doesn’t tell
you ’I am this, I am that.’ ’I am going to be this, I am going to be that.’ The
body doesn’t tell you that. What it tells you, every time something hurts, that
it is not yours, it belongs to nature.

In the moment, present experience doesn’t have a story. Where is your story in
the sense of touch? Or in the seeing, hearing, smelling, tasting? We can’t find
it. Or in the mental experience? We can’t find it.

It is a relief not having to be the hero in a story, because then we are not in
a thriller, a drama, a comedy or tragedy.

The body and its senses are just nature. It was born, it grows, it gets old, and
it dies. This is what it knows. We catch ourselves sometimes, taking it very
seriously, and we look comically bitter as though it was a job given by a film
director... so pull out those smiles you saved in the pocket from earlier.
Humour helps, it loosens the grip. We step back and laugh how absurd this
situation of being alive is.

When the stories are too complicated, return mindfulness to present experience.
Know what your experience is now. It gives us the understanding that this, here
is changing, we don’t have a lot of control over it, it is not sure, so don't
hold on. We're not sure about the rest of the story, but that's not going to be
so important any more.

One time I was out on a wandering, walking on foot in the countryside. I was
planning to walk from the monastery to the property of a friend, about 300km
distance. I was on my own, stopping in the villages to go alms-round and receive
food for the day, and then moving on. The walk was quite strenuous, and after 10
days I was already quite tired, but that's all part of it. My tendency in these
situations is to just brush it off, telling myself to tough it out, don't
complain, keep moving, you can do it.

On day 11, I received alms-food from a man and three ladies, they were very kind.
I continued walking, and in the late afternoon I was walking through a
eucalyptus plantation, it was a dirt road with a lot of cut branches lying
around. At one step, a branch got caught in my sandals in just the wrong way and
peeled off some skin from the ball of the foot. I bandaged it and the bleeding
stopped, it was a minor injury, but right on the ball of the foot, and I
couldn't stand on it. There, walking was over. 

Fortunately I wasn't so hard-headed to not have a phone with me, and I texted
the monastery with what happened, where I was, and if they could come and pick
me up the next day sometime. I wasn't in a hurry any more... 

In a few hours, friends who were staying at the monastery arrived, I was glad to
see them! Then I was thinking, isn't this better, this way the moral is not
about accomplishing a feat, but about being blessed with good friends. The
reverse would be sad in fact.

When the story is no longer about us and our achievements, what is left is
gratitude and kindness. Recollecting good actions from the past brings back the
faith in our own capacity for virtue, and when we look around we find that we
are not alone. Putting energy into cultivating these face-to-face relationships
is a deep source of happiness.

