#+TITLE: Breathing

* Notes :noexport:
* Breathing

:NOTES:
- opening
- stop and open attention
- simple message: don't suffer
:END:

#+begin_text
I remember, I used to think that during meditation we are observing the breathing
because we are supposed to learn new things from it. I sat down and struggled to
understand how to do it, and kept thinking and changing how to breathe,
expecting that eventually it will somehow work, and some day, doing it in the
right way I will start learning new facts about the mind. It was rather painful
and mostly fruitless.

The best is when we have to learn something we didn't volunteer to learn. We
don't learn new facts from meditation, because there are so few that we need,
that we probably already know them.

But we don't stop to stay with them, and unpack their significance for /what to
do/, /in what manner to do it/, or in other words /how to be/. A list of facts,
if not integrated, doesn't reach deep enough to deal with root causes in the
heart and mind, and have no effect on us. Watching the breath stops us and opens
the attention which can do that.

The Buddha only has a simple message for us: wake up, stop holding on, you don't
have to suffer. We keep unpacking this, opening it wider and wider.
#+end_text

:NOTES:
- attitude, turning inward
- complete world of feeling
- believe in causes, discover peace
- return to quiet
- restore right perspective
:END:

#+begin_text
'How can I do it?' Approach it differently, and ask instead, 'Can I pay attention
to it?'

You are only going to know it after the initial trust has allowed you to
practice, and you are only going to be able to express with knowledge what is
already behind you. That which is ahead, you can't describe it precisely,
thinking is not sufficient for that.

The sensation of breathing stops us. We are back at the beginning, when we don't
know what is going to happen. We are at an empty and spacious place this way,
where we are by ourselves and we have time to stop there.

The senses turn inward when watching the breathing. The eye sees colours, but the
seeing is directed inward, it is not seeking col or and forms outside. The ear
hears sounds, but the hearing turns inward and is not seeking. The body feels
hot and cold, the surface of clothes and the rigid weight of the bones. We watch
this while breathing and let the body calm down, let the mind turn inward and
grow still.

Consider a lake which doesn't have inlets or outlets, contained all around by
the valley, its only water-source being a fresh, cool spring in the ground. When
it rains, some water will flow into the lake through small channels, but there
being no outflow, it will all settle in the lake contained by the valley. The
water in the lake remains still, and the cool water from the spring will spread
and permeate the entire lake.

Feelings and the mind are dependent on the body, we can't add to it or take away
from it. It is complete in every breath, it start with the body and is going to
end with it. This world, made of feelings, is complete in this -- everything we
are and everything we can ever become, is contained in this.

When we suffer, we know that there is something we don't understand. We don't
understand how one thing was created by another, how one thing is under our
control, and another is not.

When we don't see, we repeat the same pattern like following a program, and create the
same suffering again and again. We complain, 'why does is always happen this way?'
We keep doing the same thing, and not see it.

Looking closer, we see that one thing depends on another. Then we can see the
option, that we are free to stop doing it. We return to a quiet contentment that
way.
#+end_text

:NOTES:
- posture
- away from everyday activities
- aware of the space
- sensation of the breath
- Bud-dho
:END:

#+begin_text
Take a few minutes to adjust how you sit and find a balanced posture. The
important point is to be upright, in a stable but not tense posture, with the
head balanced and not lulling forward, and that your posture should allow open,
easy breathing.

Determine that you are putting down everyday activities for this period. If such
a thought interrupts you, respond, 'This is not the right time, I will come back
to that when the time is appropriate. At this time, I am watching the body the
breathing.' It's a bit longer than 'Go away!', but more friendly to ourselves.
It helps to think the thought deliberately. This establishes a clear intention
in the mind, like clearing a desk before starting work. We are putting them down
not because they are not important, but because we care about doing our tasks
well. If we don't rest, we can't do our work well.

Take a deep breath and watch if you feel tension, something obstructing or
limiting the breath. If it moves easy and open, then your posture is suitable.
You don’t have to sit in a special way.

Pay attention to the physical sensation of breathing. Let the body regulate the
breath, we only watch and let it relax, giving attention to what is happening
now.

Good posture and the calm, easy breathing is a quiet and pleasant feeling, like
sitting down on a park bench after a walk. There nothing special to do, and this
simple, quiet sitting is a joy in itself.

Breathing in, we first feel the air at the nostril. The cold air moves down in
the windpipe, fill the lungs, and the chest expands. The abdomen muscles and
diaphragm move inward and outward, controlling the movement of the air. The
quiet rhythm of heartbeats can be felt. Breathing out, the muscles relax, the
chest contracts and the rib bones move closer. The warm air rises through the
wind pipe, and exits the body through the nose.

It is not necessary to express this in thought, relax and watch as the feelings
appear in the body. It takes a few minutes for the body to settle. The beating
of the heart will calm down, and the breathing will become regular and light.

Allow the body to regulate the breathing on its own. When we approach it with an
opinion, that our breathing should be short or long, then it becomes rigid and
forceful. We want to discover our experiences, not tell them what they should
be.

The body knows how to breathe better than we do. It can do breathing for us very
well, if we let it. Rather than trying to figure out whether you are breathing
correctly or not, take a step back and turn the attention around, listening
instead of directing. Breathing in, breathing out, what are you feeling in the
body?

There is no specific thing which you have to experience. The intention is rather
to have the time and allow the space to be with your experience.

Centred within itself, knowing the simplicity of the present moment. If you
feel that you have to complete, or fix something, it is always an extra,
something which we create. We create this expectation that we have to change, we
have to fix, we have to control. Notice that compulsion and recognize that you
can let it go, you don’t have to do that.

If there is a lot of tangled thinking, determine what to think, instead of
letting the mind run in circles. For example, use the mantra BUD-DHO, which
means 'the one who knows'. On the in-breath, think BUD-, on the out-breath,
-DHO. If we have already built up a strong momentum in the thinking, and it
refuses to quiet down, this puts down a guard rail and speed bumps on the road,
so that we stay on track and slow down.
#+end_text

:NOTES:
- simple experience of the present
:END:

#+begin_text
Breathing in, staying with the simple experience of the moment, and this is
enough.

We feel compulsions, desires and anxieties, we feel 'I need this', 'I am like
this', 'I should be like that' -- they are something we can observe. Staying
with the breathing, we can turn attention to the experience that is happening.

Awareness of the body is a solid base, calming and reorganizing what is
valuable. If your experience is peaceful, happy and content, stay with that.
There is nothing wrong in that. It is a happiness which is not connected to
craving, not dependent on having to get or reach something. It is a happiness
arising from seclusion of the senses, returning to simplicity, knowing and
staying with the present. The mind is alert, content, and satisfied.
#+end_text

:NOTES:
- generosity relaxes
:END:

#+begin_text
If you find yourself in a tense, strict and cynical mood, I recommend shift your
posture slightly to relax, quietly rub your ears or massage the face muscles
using your fingers, and recollect generosity. In the monastery, it is frequently
the lay friends who come to cook and offer the midday meal for the community.
They can be busy while in the kitchen, but when finished, they are at ease,
relaxed and smiling.

Recollecting our good actions, even simple and small things, relaxes the mind
which is thirsty for results. Imagine what would happen, if someone gave you a
hundred-times-fold of what you need. How are you going to meditate then?
Probably much like now, just more relaxed. Grant yourself that rich, wide space.

Generosity lets us recognize that we have space, and don't have to push get
ahead of others, there is goodness in the world and we can drop the big hurry.
It also feels joyful to recollect the generosity of our family, relatives and
friends, but even seeing a stranger help another stranger brings us to smile.
#+end_text

:NOTES:
- closing
- towards the end we want to complicate it
- begin again, where you didn't expect to know
:END:

#+begin_text
When we have been sitting in meditation for a while, we often start to
complicate it. Where does this come from, that we can't stay with something
simple? Notice how belief in the simple changes, we start thinking about some
point, and the doubt and self-criticizing stops everything.

It is comical, how we can be so committed to our self-criticism, as if it was a
transcendental experience to cause ourselves pain. But we feel we should be
struggling with /something/, we should crush our ego and let go of everything.
Perhaps this is the only way we know, we don't even know what it could be like
to not be like this.

At the beginning we have the kind and flexible attitude to ourselves, but there
is only hardness and judgement at the end. The young tree is pliant and fresh,
it bends easily as it grows, but the old tree is hard and dry when it dies.

Return to the beginning, where there is kindness to the beginner, where you
didn't yet expect yourself to know. We don't know what is here until we look and
see. That seeing and watching is the fresh knowing. Allow yourself to be always
at the beginning.
#+end_text
