#+TITLE: Légzés

* Légzés

:NOTES:
- opening
- stop and open attention
- simple message: don't suffer
:END:

:NOTES:
- attitude, turning inward
- complete world of feeling
- believe in causes, discover peace
- return to quiet
- restore right perspective
:END:

#+begin_text
'Hogy tudom megcsinálni?' Közelítsd meg másként, és inkább azt kérdezd, 'Tudok
rá figyelni?'

Ismerni csak azután fogod, hogy a kezdeti bizalom engedett gyakorolni, és azt tudod majd
kifejezni ami már mögötted van. Ami jön, azt nem tudod ismerettel leírni, a
gondolat erre nem elegendő.

A légzés érzete megállít. Visszakerülünk az elejére, ahol nem tudjuk mi lesz.
Egy üres és tágas helyre kerülünk így, magunk vagyunk és van időnk itt megállni.

TODO: lake water

A légzésre figyelve az érzékek befelé fordulnak. A szem látja a színeket, de a
látás befelé irányul, nem akar kívül színeket és formákat keresni. A fül hallja
a hangokat, de a hallás befelé fordul és nem keres. A test érzi a hideget,
meleget, a ruhák felületét és a csontok merev súlyát, a légzés közben figyeljük
ezt és hagyjuk a testet lenyugodni, hagyjuk az elmét befelé fordulva elcsendesedni.

Ez az érzés világa ebben teljes, minden ami vagyunk, vagy amivé valaha
válhatunk, ezen belül van. Az érzés és tudat a testtől függ, nem tudunk
hozzátenni vagy elvenni belőle. Minden légzésben teljes, a testtel kezdődik és
azzal lesz vége.

Az érzés és tudat a testtől függ, nem tudunk hozzátenni vagy elvenni belőle.
Minden légzésben teljes, a testtel kezdődik és azzal lesz vége. Ez világ, ami
érzésekből áll, ebben teljes, minden ami vagyunk, vagy amivé valaha
válhatunk, ezen belül van.

Amikor szenvedünk, tudjuk, hogy van itt valami, amit nem értünk. Nem értjük,
hogy egy dolog hogyan jött létre a másikból, hogy egy dolog az irányításunk
alatt van, a másik pedig nincs.

Amikor nem látjuk, ugyanazt a mintát ismételjük mint egy program, és ugyanazt a
szenvedést újra és újra létrehozzuk. Panaszkodunk, hogy 'Miért van ez mindig
így?' Ugyanazt a dolgot tesszük újra és újra, és nem látjuk.

Közelebbről megnézve látjuk, hogy az egyik dolog a másiktól függ. Akkor szabadon
abbahagyhatjuk. Így visszatérünk a csendes elégedettséghez.
#+end_text

:NOTES:
- posture
- sensation of the breath
- [ ] away from everyday activities
:END:

:NOTES:
- simple experience of the present
:END:

:NOTES:
- closing
- towards the end we want to complicate it
- begin again, where you didn't expect to know
:END:

