#+TITLE: Breathing

* Notes :noexport:
* Breathing

:NOTES:
- opening
- stop and open attention
- simple message: don't suffer
:END:

#+begin_text
I used to think that we are supposed to learn new things by observing the
breathing. I sat down and struggled to understand how to do it, and kept
thinking and changing how to breathe, expecting that eventually it will somehow
work, and some day, doing it in the right way I will start learning new facts
about the mind. It was rather painful and mostly fruitless.

The best is when we have to learn something we didn't volunteer to learn. We
don't learn new facts from meditation, because there are so few that we need,
and we already know them. But we don't stop to stay with them, and unpack their
significance for /what to do/, /in what manner to do it/, or in other words /how
to be/. A list of facts, if not integrated, doesn't reach deep enough to deal
with root causes in the heart and mind, and have no effect on us. Watching the
breath stops us and opens the attention which can do that.

The Buddha only has a simple message for us: wake up, stop holding on, you
don't have to suffer. We keep unpacking that.
#+end_text

:NOTES:
- attitude, turning inward
- complete world of feeling
- believe in causes, discover peace
- return to quiet
- restore right perspective
:END:

#+begin_text
'How can I do it?' Approach it differently, and ask intead, 'Can I pay attention
to it?'

You are only going to know it after the initial faith has allowed you to
practice, and you are going to be able to express what is already behind you.
That which is ahead, you can't describe it with knowledge, thinking is not
sufficient for that.

The sensation of breathing stops us. We are back at the beginning, when we don't
know what is going to happen. We are at an empty and spacious place this way,
where we are by ourselves and we have time to stop here.

Consider a lake which doesn't have inlets or outlets, contained all around by
the valley, its only water-source being a fresh, cool spring in the ground. Some
water might flow in from showers, but there being no outflow, it will flow down
and settle within the contained area. The lake-water remains still, and the cool
water from the spring will fill and permeate the entire lake.

The senses turn inward when watching the breathing. The eye sees colors, but the
seeing is directed inward, it is not seeking color and forms outside. The ear
hears sounds, but the hearing turns inward and is not seeking. The body feels
hot and cold, the surface of clothes and the rigid weight of the bones, we watch
this while breathing and let the body calm down, let the mind turn inward and
grow still.

Feelings and the mind are dependent on the body, we can't add to it or take away
from it. It is complete in every breath, it start with the body and is going to
end with it. This world, made of feelings, is complete in this, everything we
are and everything we can ever become, is contained in this.

When we suffer, we know that there is something we don't understand. We don't
understand how one thing was created by another, how one thing is under our
control, and another is not.

When we don't see, we repeat the same pattern like a program, and create the
same suffering again and again. We complain, 'why does is always happen this way?'
We keep doing the same thing, and not see it.

Looking closer, we see that one thing depends on another. Then we are free to stop doing it.
We return to a quiet contentment that way.
#+end_text

#+begin_export html
#+end_export

:NOTES:
- posture
- away from everyday activities
- aware of the space
- sensation of the breath
- Bud-dho
:END:

#+begin_text
Take the time to adjust the body and find a good sitting or standing posture.
The important point is to be upright, in a stable but relaxed posture, with the
head balanced and not lulling forward, and to allow the breathing to be open.

Determine that you are putting down everyday activities for this period. 'This
is not the right time, I will come back to that at its proper time.' Putting
them down not because they are not important, but because if we don't rest, we
can't do our work well. It can help to think the thought deliberately. This
establishes a clear intention, and communicates to the unconscious processes in
the mind, like clearing away clutter from a desk before starting work.

Take a deep breath to test how the body moves. If you don’t feel anything which
is obstructing and limiting, if the breath is easy and open, then that will do.
You don’t have to sit in a special way.

Pay attention to the sensation of breathing. Let the body regulate the breath,
we only watch and notice. Giving attention to what is happening.

Good posture and the happiness of breahing easily is a quiet and pleasant
experience, like sitting down on a park bench after a walk. There nothing
special to do, and the simple sitting is a joy in itself.

Breathing in, the breath touches the nostril. The cold air is coming down into
the lungs. The chest expands as the muscles pull in the fresh air. Breathing
out, the muscles relax, the bones of the ribcace contract and the warm air rises
through the wind pipe, and exits the body through the nostril.

It takes a few minutes for the body to settle. The beating of the heart will
calm down, and the breathing will become even and regular.

Allow the body to regulate the breathing on its own. When we have an opinion,
that my breathing should be short, or it should be long, then it becomes
forceful. We want to discover our experience, not tell it what it should be.

The body knows how to breathe better than we do. It can do breathing for us very
well, if we let it. Rather than trying to figure out if you are doing it right,
step back and turn the attention around, and watch the feelings of the body move
like clockwork. Breathing in, breathing out, what are the feelings in the body?

There is no specific thing which you have to experience. It is rather to have
the time and allow the space to be with your experience.

Centered within itself, knowing the simplicity of the present moment. If you
feel that you have to complete, or change something, it is always an extra,
something which we create. We create this expectation that we have to change, we
have to fix, we have to control. Recognize that compulsion and recognize that
you can let it go, you don’t have to do that.

If there is a lot of thinking, determine what to think, instead of letting the
mind run in circles. For example, use the mantra BUD-DHO, which means 'the
knowing'. On the in-breath, think BUD-, on the out-breath, -DHO. Thoughts can
have a lot of momentum, and refuse to quiet down, but this puts down a guard
rail and speed bumps on the road, to slow down and stay on track.
#+end_text

:NOTES:
- simple experience of the present
:END:

#+begin_text
Breathing in, staying with the simple experience of the moment, and this is
enough.

The compulsions and desires which we feel that we need, or the anxieties we feel
we have to fulfil, they are something you can observe. Staying with the
breathing, you can turn attention to feeling that experience that you have.

If your experience is peaceful, happy and content, stay with that. There is
nothing wrong with that. It is a happiness which is not connected to craving,
not dependent on having to get or gain something. It is a happiness arising from
seclusion of the senses, withdrawing to simplicity, and knowing the present
moment. That is an alert, content, and satisfied state of mind.
#+end_text

:NOTES:
- generosity relaxes
:END:

#+begin_text
If you find youself in a tense, strict and cynical mood, I recommend shift your
posture slightly, quietly rub your ears or massage the face muscles, and
recollect generosity. In the monastery, it is frequently the lay friends who
come to cook and offer the midday meal for the community. They can be busy while
in the kitchen, but they are always relaxed and happy when finished.

Recollecting good actions we have done relaxes the mind which is thirsty for
results. Imagine someone gave you a hundred-times-fold of what you need. How are
you going to meditate then? Probably much like now, just more relaxed. Grant
yourself that richness.

Generosity lets us recognize that we have space, and don't have to push get
ahead of others, there is goodness in the world and we can drop the big hurry.
Recollecting the generosity of friends and relatives is also joyful, but even
seeing a stranger help another stranger brings us to smile.
#+end_text

:NOTES:
- closing
- towards the end we want to complicate it
- begin again, where you didn't expect to know
:END:

#+begin_text
When we have been sitting for a while, we start wanting to complicate it. Where
does this come from, that we can't stay with something simple? Notice how belief
in the simple changes, there is some point we start thinking about, the doubt
and self-criticizing stops everything.

It is comical, how we can be so committed to our self-criticizm, as if it was a
transcendental experience to cause ourselves pain. But we feel we should be
struggling, we should crush our ego and let go of everything.

Why is it OK to think hostile thoughts to ourselves, but not OK to be supportive
to ourselves and trust what is simple? The Buddha's message is simple, but goes
a long way. It takes a long time to unpack, and we benefit even from a small
bit.

There is kindness to ourselves and flexibility at the beginning, but there is
only hardness and judgement at the end. The young tree is pliant and fresh, it
bends easily as it grows, the old tree is hard and dry when it dies.

Begin again, where there is kindness to the beginner, where you didn't expect
yourself to know. We don't know what is here until we watch and see. That seeing
and watching is the fresh knowing. Allow yourself to be always at the beginning.
#+end_text
