#+TITLE: Csónak

* Csónak

:NOTES:
- simplify it down to the essence
:END:

#+begin_text
Meditation techniques are useful, they let us learn by doing, but we learn the
techniques not for knowing the techniques, but for knowing the mind. Too many
techniques, or complicated steps and sequences however are confusing, and lead
to a sense of being lost.

Egyszerűsítsd le a lényegre. Egy lélegzet, egy BUD-DHO. Belégzésre ismételd
magadban a mantra felét, BUD-, középen a megállás, kilégzésre, -DHO. BUD-DHO.
Kész.

A lényeg a béke, és a megértés, ami megállít.

A béke abból ered, hogy az érzékek visszahúzódnak és befelé néznek. A keresés
megáll, mert ami van elég, és sehova nem kell menni. A csendes öröm abból fakad,
hogy az elme megérti, hogy nincs boldogság amit a világban hajszolni kell. Az
értékek átrendeződnek.

Hol van a béke most? Hol van a megértés most? Semmit nem kell megoldani.
BUD-DHO, tíz lélegzet, és vége a világnak. Elég, ha a kérdés megállítja az
elmét. Ez a megállás a figyelő csend, a válasz pedig nem szükséges.

Hétköznapi helyzetben, egyszerűsítsd le, amíg mindig felismerhető. Teljesen
fáradt vagy, semmi energiád, kavarog az agyad a napi jövés-menéstől, de a légzés
akkor is elérhető, a csend ott is érezhető.
#+end_text

