#+TITLE: Csontok

* Csontok
 
:NOTES:
- bodily awareness stops anger
:END:

#+begin_text
Watching the body...

A testi tudatosság megállítja a haragot, neheztelést és belső vádaskodást.
Gondolkodva csak jobban beássuk magunkat, de ezt ilyenkor nem látjuk. Valahogy
fontosnak érezzük, hogy mérgesek legyünk, pedig csak az idő telik el vele
fájdalmasan. Arra vágyunk, hogy vége legyen és nyugodtan mehessenek a dolgok
tovább.
#+end_text

:NOTES:
- no stories
- stories in an old book
- interpreting somebody else's dream
- time-travelling back to the present
- resolution starts
:END:

#+begin_text
Megfigyeljük a test részeit, és látjuk, hogy nem hordoznak magukkal semmilyen
sztorit. Így fellélegezhetünk, hogy nem vagyunk a sztorikhoz láncolva, azokat mi
hozzuk létre.

Ehhez a figyelemhez mindig vissza tudunk térni, egy belégzés és kilégzés elég
ahhoz, hogy emlékezzünk a keletekzésre és elmúlására, és a problémáink olyanná
válnak, mint a sztorik egy régi újságban. Ráununk kibogozni a szálakat, mintha
valaki más álmait kellene értelmeznünk. Ami a valóság, az mindig itt van a jelen
tapasztalatunkban. Nem az válik fontossá, hogy mi a sztori, hanem az, hogy
a figyelmünket annak tudjuk szentelni, ahol most vagyunk.

A testi tudatosság enged a kívánságokból és rávezet arra, hogy szerencsések
vagyunk, hogy itt lehetünk.

Hova akarunk jutni? Elkezdhetjük most. Ha valóban érdemes dologról van szó,
szinte biztos, hogy nehéz is. Ha nehéz, szinte biztos, hogy nem tudjuk mit kell
tenni. A bizonytalanság a terv része kell legyen.

Elkezdeni viszont valószínűleg nem bonyolult. Megkérdezhetjük magunkat, hogy ha
lenne időgépünk, visszamennénk pár évvel, hogy már akkor elkezdjük? Ha már pár
évvel ezelőtt elkezdtük volna, örülnénk annak, hogy mostanra már legalább van
némi ismeretünk a helyzetről. A mostban a jövőbeli önmagunknak tehetjük meg ezt
a szívességet. Elkezdhetjük most, és elképzelhetjük, hogy pár év múlva
visszanézünk, és megköszönjük magunknak, hogy elkezdtük eloszlatni a ködöt.

Amikor nincs tisztán elhatározott szándékunk, csak úgy sodródunk, és /nem
kifejezetten zavar/ minket, hogy itt vagyunk, de az elme szürke és élettelen,
szinte próbál elbújni és láthatatlanná válni. Az eredmény, hogy valóban szürkévé
és láthatatlanná válunk így. Semmi rossz nem történik, de nincs semmi világosság
sem abban, hogy ott vagyunk.

Visszanézve a jelenre a jövőbeli önmagunk szemével, visszajönnénk, mert itt
/akarunk/ lenni? Lehetünk cinikusak és gondolhatunk a legrosszabbra, de meglepő
módon, a válasz gyakran nem a helyzetet kezdi el boncolgatni, hanem mint amikor
új helyre utazunk, hálásak vagyunk, hogy ilyen szerencsések vagyunk, hogy itt
lehetünk ahol vagyunk. Van amit még később meg kell tenni, de már azért is
köszönetet tudunk mondani, amit eddig megtapasztalhattunk.

Nem állunk meg elég gyakran, hogy észrevegyük mikor boldogok és nyugodtak
vagyunk. Amikor az elme tiszta és csendes, természetes módon hálás azért ami itt
van, és képes köszönetet mondani az áldásokért amit életünkben kaptunk. A jelen
jó, és akárhogy is alakul az életünk hátralevő részében, meg tudjuk azt
köszönni.

Nem létrehozunk valamit, hanem tiszta szándékkal felismerjük azt ami itt van.
Nem erő vagy képesség kérdése, ezek időhöz és körülményhez kötöttek. Az
elhatározás, a befelé irányuló flismerő figyelem nem egy adott körülményhez
kötött. Az eredménye a helyes szemlélet, amiben látjuk a dolgok megfelelő
helyét, és mit kell azokkal tenni -- vagy csak megállni, figyelni és lélegezni.
#+end_text
