#+TITLE: Boat

* Boat [0/7]

:TOPICS:
- simplify it down to the essence
:END:

#+begin_text
Meditation techniques are useful, they let us learn by doing, but we learn the
techniques not for knowing the techniques, but for knowing the mind. Too many
techniques, or complicated steps and sequences however are confusing, and lead
to a sense of being lost.

Simplify it down to the essence. One breath, one BUD-DHO. On the in-breath,
think the first half of the mantra, BUD-, a pause in the middle, and on the
out-breath, -DHO. BUD-DHO. Done.

The essence is peace, and the understanding, which stops you.

The peace originates from the senses drawing in and turning inwards. The seeking
stops, because what is here is enough, and there is no need to go anywhere. The
quiet joy arises from the mind which understands that there is no happiness in
the world to be pursued. The values re-organize themselves.

Where is the peace now? Where is the understanding now? There is nothing to
solve. BUD-DHO, ten breaths, and the world ends. It is enough, when the question
stops to mind. This pause is the listening silence, and the anwser is not
necessary.

In an everday situation, simplify it down, until it is clear to recognize. You
are completely exhausted, you have no energy, your mind is spinning with the
coming and going of the day, but the breath is still available, the silence can
be still felt.
#+end_text

:TOPICS:
- bail out the boat
- things are empty
- bailing out the boat
- not heavy with self
:END:

#+begin_text
One of the teaching images of the Buddha is bailing out the boat. Imagine when
a boat or ship is full of water, or full of goods it has to carry, then the
boat moves slowly. It is burdened, heavy and slow, all the water and things are
weighing it down.

We would like our boat to go fast, don't we? But at the same time we are holding
onto everything that is in it. We have to lighten the boat, give up the self
which is the heavy burden. We create ’me’ and ’mine’, we create ’what I have to
be’, ’what I should be’, ’what I am’. This is what is holding to boat down, this
is the weight.

Emptiness is when the boat is empty. It moves swiftly, because it is light as a
feather, not heavy with self, the story and drama of ’me’ and ’mine’.
#+end_text

:TOPICS:
- happy, here
- afraid to open
:END:

#+begin_text
Often just stopping to look is enough to notice that we are happy where we are.
Stop and stay with it. A lot of us think we are never happy.

But when we are suffering, we know that there is something to learn, something
to understand, the attachment is hiding somewhere.

Letting go is not always cutting off. Sometimes we are telling ourselves to let
go, because we are afraid to open or commit ourselves, and depriving ourselves
pleases our self-critical mind. This ill-will and anger toward ourselves is
self-destructive.

See through the trick, the judgement that 'this is not ultimately
transcendental', which stops you from doing something good, how is that
wholesome?

Sometimes letting go means to let go of the fear to pull out all the stops and
do your best. Not because it is useful, not because somebody expects it, but
because you know it is the right thing to do, and you love doing what you do.
#+end_text

:TOPICS:
- map story
:END:

#+begin_text
One time I was walking in the countryside, and I had sheets of paper maps with
me. I had been walking for a few days, and I usually make notes on the map,
track which paths I followed, where did I find a good camping spot, where did I
receive alms-food in the village and so on, it is a kind of log or journal. When
I get back to the monastery, I scan the maps and type up the notes.

This was a rainy and windy day, and I was walking in the middle of nowhere on
the muddy roads. I sat down to rest, and I thought, 'let's mark up this last
section of the route on the map.' I kept the map sheets in a plastic folder. I
take a look, and I can see today's map, but yesterday's map is not there. /I've
lost yesterday's map./ With all the notes.

I must have dropped it sometime earlier when pulling out today's map for a look.
It could be kilometers behind me, in the mud somewhere, or the wind must have
blown it into some corner. /I've lost yesterday's map./ I felt so shaken, it was
comically absurd. I couldn't remember the last time I was so disappointed.

The Sun was going to set soon, and I still had a lot of distance to walk. The
next morning I had to reach the next town, otherwise I can't go alms-round and I
don't eat that day. (The monk's rules don't allow us to store food from one day
to the next.)

So I couldn't easily turn around and start tracing my way back. I was sitting
there, thinking, 'I should let go. It's just some notes. This is just a state of
mind, a good monk should let go.'

But all that didn't sit right. I thought, 'What am I afraid of here? Why is it
wrong to like that piece of paper? Why is it OK to be critical, but not OK to
like myself? I love doing what I do, and I'm going back for my map.'

I found it about 500m behind me. It was floating in a puddle, soaked, but
intact. I lifted it like it was an archaeological artefact.

That day I learnt more than I volunteered for. I rolled it up in a towel and it
dried eventually. It was almost dark by the time I found a place to camp but
everything was well. Next day I did get to the town in time for alms-round, a
man and two ladies offered me food for the day.
#+end_text

:TOPICS:
- sail swiftly
:END:

#+begin_text
What lets the boat sail swiftly without obstruction?

Taking on everything is clearly not it, becuase the boat is going to sink on the
way. On one hand, keeping the wish-list short, on the other, deciding the
negative space of a work is just as useful, that is, what is it that we are not
going to include, what is not going to be our problem to solve.

Setting boundaries to create structures in a way that allows us to suffer less,
and allow others to suffer less. If we take on everything around us, the boat
will sink even before leaving the port. That can't help us, and can't help
others either.
#+end_text

:TOPICS:
- [ ] Picking up a responsibility
- [ ] self-respect
- [ ] hospital care
- [ ] carry your weight
- [ ] We can't grow stronger if we don't carry our weight, and others can't grow stronger -- carry weight is self-respect
:END:

:TOPICS:
- road to success
:END:

#+begin_text
The Buddha taught the factors which lead to success. The energy to move and do
something toward a goal depends on the faith that it makes sense, and the
resolution to put effort into it. Doubt and criticism stops everything. We don't
have to know it will work, we will only know that after we finished.

It is enough to consider that we invesitaged the situation sufficiently to make a
start. The plan will change anyway when we meet the circumstances and recognize
what needs to be solved.

If we consider the worst possible outcome that is reasonable to expect and we
prepare for it, that gives us enough resolution to start. Investigating the
circumstances, we resolve to do it. Determining the tasks which need doing,
putting in the effort to keep the momentum going, keeping the sails in the wind.
#+end_text

:TOPICS:
- [ ] not what we think, what we do

If we want a picture of ourselves, we 
our actions
other's actions to us
how the world behaves

learn from actions
reflect on actions
:END:

:TOPICS:
- closing the door gently
- [ ] quote reference
:END:

#+begin_text
There are times when investigation tells us to stop. Things change while we are
not looking, not waiting for us. Grateful for having been there, there is a
subtle art in gently closing the door behind us when leaving a room, and moving
on in silence.
#+end_text

