#+TITLE: Bones

* Notes :noexport:

 - restore view; life, the whole of it; a baby and the ash urn are same weight

* Bones [0/2]

:TOPICS:
- the bones as the fixed parts
- at the core
- kindness and acceptance
:END:

#+begin_text
The bones are fascinating because they show the core, the fixed part of the body
which determines what it is, what it can and cannot do.

It is also frightening because seeing bones reminds us of the suffering of
losing what we know, but they also teach us what we don't know -- how to not
create that suffering with kindness and acceptance, and this is where the
meditation on bones open a way.

No matter what we think of the surface, the bones give us a message from beyond
our thinking, that there is no ideal state about that surface.
#+end_text

:TOPICS:
- standing posture
- head balance
:END:

#+begin_text
Meditating in the standing posture, it is easy to feel the the bones of the
body.

In standing, you have to put in a bit more effort to maintain the posture. Sway
the body a bit and feel the weight. Develop that sense that there is something
you have to hold. Relax the knees and let them bend a bit. Don’t lock them
straight, that stresses the joints and your posture becomes rigid.

Feel out the balance and notice there is a body which you are holding up. There
is a pressure on the ground, gravity is pulling it down. Let the hands down on
the side if that is comfortable, or collect them in front of the abdoment if
that feels better.

Watch the posture. Notice how you are standing. Take a deep breath, watch how
the bones move. This is the mechanics of breathing. Is there something limiting
it? Notice if you are standing straight, or if the shoulders are hunched,
perhaps tired. Watch the balance of the head, find the position where the head
sits on top of the spine by its own weight. Pulling in the chin gently, and the
crown of the head pushing the sky.

The head controls the shape of the spine to a great degree. Because of sitting
on chairs, we fall into a habit of carrying the head in a manner pushed forward.
This creates a tension in the back muscles. Experiment, what does it feel like,
to pull the head back a bit. The muscles in the back relax.
#+end_text

:TOPICS:
- bones
- body made of pieces
:END:

#+begin_text
Feel how the bones connect. There is this perception of an inner structure which
supports the body from the inside. Rigid pieces, stacked on top of each other.
There is a sensation in the legs, a rigid perception, which are the long leg
bones. There is pressure. The hip bone is resting on top of the legs, the torso
moves joined on to it. The ribcage expands and contracts with the breathing. The
spine is holding the weight in a curve. The head is sitting on top of the spine.
The skull bones are streching the skin on the face.

It is made out of pieces. Pieces that in some places hard and rigid, and some
places soft and flexible, these give it shape. There is hair on top of the head.
Some hair on the hands and other parts.

The habitual perception of the body, of our body and of other people's body, is
that we see it as one unit, as one thing. Trom that perspective develops an
obsession that it has some ideal way to be. That it has to be a certain shape,
height, different qualities.

These are wordly judgements, perceptions which our society drill into us.
Advertisements and media messages reinforce these expectations and we believe in
them, but when we look closer we see this is a twisted perception, not according
to reality.

These social expectations create an anxiety about our appearance, we are
concerned about what other people think about our body, and we create opinions
about their bodies.
#+end_text

:TOPICS:
- hair and nails dropping on the ground
:END:

#+begin_text
We can watch how this anxiety is conditioned when parts of the body are
separated. We can be concerned about our hair for example, but only when it is
on our head. When it is cut off, we are not anxious about a pile of hair on the
ground. Similarly, when cutting our nails, what is that point when it is no
longer 'me' and 'mine'?

When we contemplate it this way, as something made up of pieces, we can see the
body is not one unit, it is made of pieces and parts which have their own
nature, and behave according to that, not concerned with our opinions or others.
Bones, skin, hair, teeth and nails, they are the way they are. Contemplating
this gives us confidence in accepting them with kindness.

The body is a blessing. This meditation is not to develop aversion or negative
emotions toward the body. Health is a blessing, it supports us in everything we
do. The Buddha called health the greatest treasure.
#+end_text

:TOPICS:
- bodily awareness stops anger
:END:

#+begin_text
Breathing in, breathing out, attention is turned inwards, noticing 'there is a
body'. The mind is not seeking anything, not going out somewhere. From the feet,
to the legs, abdomen, chest, arms, the skull and the head, you can feel the skin
as it is streched against the bone of the skull.
  
Watching the body like this is like watching the rain, there is nothing to do,
nothing to decide, and rain goes on without us having to get involved.

Awareness of the body stops the anger, resentment and inner blaming. There is no
escape. Continuing the thinking we only dig ourselves deeper, but we can't see
that at the time. Somehow we feel it is important to be angry, although only the
time passes painfully with it. We wish for it to be over finally, and let things
continue smoothly.
#+end_text

:TOPICS:
- no stories
- stories in an old book
- interpreting somebody else's dream
- time-travelling back to the present
- resolution starts
- [ ] a scar is not a story
- [ ] time travel quote reference
:END:

#+begin_text
We observe the parts of the body and see that they don't carry a story with
them. We can breathe a sigh of relief that we are not chained to the stories, we
are creating them.

We can always return to this attention, one in-breath and out-breath is enough
to remember arising and ceasing, and our problems become like stories in an old
newspaper. We get tired of untangling the threads, as if we had to interpret
someone else's dreams. What is real, is always here in our present experience.
What becomes important is not what the story is, but whether we can give our
attention to where we are now.

Awareness of the body loosens the desires and leads us to recognize that we are
fortunate to be here.

Where do we want to get to? We can start now. If it is a truly worthwhile thing,
it is almost certainly difficult as well. If it is difficult, it is almost
certain we don't know what to do. Uncertainty has to be part of the
plan.

However, is it probably not complicated to start. We can ask ourselves, if we
had a time-machine, would we go back a few years, so that we can start then
already? If we had already started a few years agos, we would be glad that by
now, at least we have some information about the situation. In the present, we
can do this favour for our future self. We can start now, and imagine, that in a
few year's time we look back and thank ourselves, to have started to clear the
fog.

When we don't set a clear intention, we are just drifting, and /we don't
particulary mind/ being here, but the mind is a gray with no life, almost trying
to hide itself and be invisible. We do end up being gray and invisible like
that. There is nothing wrong happening, but there isn't any brightness in being
there.

Looking back on the present with the eyes of our future self, would we come
back, because /we want/ to be here? We can be cynical and think of the worst,
but surprisingly often the answer doesn't start analysing the situation, but
instead, like when we travel to a new place, we are grateful that we are
fortunate to be here where we are now. There are things to do later, but we can
already say 'thank you' for what we could experience until now.

We don't stop often enough to notice when we are happy and peaceful. When the
mind is clear and calm, it is naturally grateful for what is here, it is able to
say 'thank you' for the blessings we received in our life. The present is good,
and whatever way it develops for the rest of our life, we are able say 'thank
you'.

We are not creating something, with a clear intention we recognize what is here.
It is not a matter of strength or ability, these are bound to time and
circumstance. The resolution, the recognizing attention turned inwards, is not
bound to a give circumstance. The result is right perspective, in which we can
see the right place of things, and what to do with them -- or to just stop, give
attention and breathe.
#+end_text

