#+TITLE: Csontok

* Csontok
 
:TOPICS:
- bodily awareness stops anger
:END:

#+begin_text
Watching the body...

A testi tudatosság megállítja a haragot, neheztelést és belső vádaskodást.
Gondolkodva csak jobban beássuk magunkat, de ezt ilyenkor nem látjuk. Valahogy
fontosnak érezzük, hogy mérgesek legyünk, pedig csak az idő telik el vele
fájdalmasan. Arra vágyunk, hogy vége legyen és nyugodtan mehessenek a dolgok
tovább.
#+end_text

:TOPICS:
- no stories
- stories in an old book
- interpreting somebody else's dream
- time-travelling back to the present
- resolution starts
:END:

#+begin_text
Megfigyeljük a test részeit, és látjuk, hogy nem hordoznak semmilyen sztorit.
Így fellélegezhetünk, hogy nem vagyunk a sztorikhoz láncolva, azokat mi hozzuk
létre.

Ehhez a figyelemhez mindig vissza tudunk térni, egy belégzés és kilégzés elég
ahhoz, hogy emlékezzünk a keletekzésre és elmúlására, és a problémáink olyanná
válnak, mint a sztorik egy régi újságban. Ráununk kibogozni a szálakat, mintha
valaki más álmait kellene értelmeznünk. Ami a valóság, az mindig itt van a jelen
tapasztalatunkban. Nem az válik fontossá, hogy mi a sztori, hanem az, hogy
tudjunk arra figyelni, amikor itt vagyunk.

A testi tudatosság enged a kívánságokból és rávezet arra, hogy szerencsések
vagyunk, hogy itt lehetünk.

Hova akarunk jutni? Elkezdhetjük most. Ha nehéz dologról van szó, szinte biztos,
hogy nem tudjuk mit kell tenni, de elképzelhetjük magunkat, hogy pár év múlva
visszanézünk a mostra, és megköszönjük magunknak, hogy elkezdtük eloszlatni a
ködöt.

A jövőbeli önmagunk szemével visszanézünk a jelenre, és megkérdezzük, itt
akarunk lenni? Meglepő módon a válasz gyakran nem a helyzetet boncolgatja, hanem
hálás azért, hogy ilyen szerencsések vagyunk, hogy itt lehetünk ahol vagyunk.
Van amit meg akarunk még tenni, de már azt is meg tudjuk köszönni, amit eddig
megtapasztalhattunk.

We don't stop often enough to notice when we are happy and peaceful. When the
mind is clear and calm, it is naturally grateful for what is here, it is able to
say 'thank you' for the blessings we received in our life. The present is good,
and whatever way it develops for the rest of our life, we are able say 'thank
you'.

Az elhatározás, hogy figyelni fogunk, megteremti ennek a kellő feltételt. Nem erő
vagy képesség kérdése, ezek helyhez és időhöz kötöttek. Az elhatározás, a befelé
irányuló flismerő figyelem nem egy adott körülményhez kötött. Az eredménye a
helyes szemlélet, amiben látjuk a dolgok megfelelő helyét, és mit kell azokkal
tenni -- vagy amikor nincs más teendő, csak megállni, figyelni és lélegezni.
#+end_text
