#+TITLE: Ciklusok

* Ciklusok

:TOPICS:
- more technique, what to do, how to do more
- steps and techniques
- not linear, cycles
- these cycles ignore our ideas about progress
- not a meditation carreer
- the harder we push the more pain we are in
- knowledge doesn't become yours
:END:

#+begin_text
A meditáció a jelenbeli érzéseken, tapasztalatokon keresztüli megismerést tanítja.

Az utasítások lépésekben épülnek fel, de nem ezek a lépések a meditáció célja,
hanem a jelen tapasztalat tiszta ismerete, a helyes nézőpont visszaállítása.
Kialakulhat bennünk az a benyomás, hogy mindig ugyanazt a lépés sort kell
teljesítenünk, és amikor az elme nem aszerint a sorrend szerint fejlődik,
csalódottak vagyunk.

Fordístd meg ezt a hozzáállást és kezd a tapasztalattal. Ha a tapasztalat az
alap, ahogy a dolgok vannak, az milyen megértést ad nekünk? Amikor falat
festünk, először megvizsgáljuk a falat, kiválasztjuk hozzá a megfelelő festéket,
és /azután/ követjük a tanácsokat a dobozon. A rossz festék csak le fog válni,
nem? Először az elmét vizsgáljuk, hogy érezzük magunkat, milyen állapotban
vagyunk, és arra válaszolunk intelligensen.

A meditáció a jelenbeli érzéseken, tapasztalatokon keresztüli megismerést tanítja.

A lépések az imitációs tanulás részei, egy példát követve figyeljük önmagunkat
és meglátjuk mi hogy működik. Amikor fájdalmat és szenvedést érzünk, és vagy fel
tudjuk oldani, vagy türelmesen kivárni, akkor tudjuk, hogy ez nem csupán
imitáció volt, és a gyakorlásba vetett bizalmunk erősödni fog. Ebből tanultunk
valamit, és nem ragaszkodunk az első bemutató részleteihez.

It would be great if our meditation would develop in a linear way...
#+end_text

