#+TITLE: Ocean

* Ocean

:TOPICS:
- different form of cognition
- ocean, wider space
- grateful for solitude
- present is interesting when you look
:END:

#+begin_text
Bodily awareness is a different form of cognition. It is not thinking, not
seeking solutions, not trying to answer questions, just an awareness which knows.

Remember what it is like, when you are watching the ocean. The thinking stops.
The ocean is unfathomable, changing and moving, it cannot be enclosed with fixed
thoughts.

This open awareness solves problems not by providing anwsers, but by giving us
the perspective that this is happening in a wider space. Happiness and suffering,
success and disappointment is happening in this, and by seeing this we know that
this not what we are.

We can be grateful for just being with ourselves. For the solitude of being with
ourselves in the moment, for having the time to be, for having the space to
accept.

The present moment is always interesting. When you feel that it is not
interesting, try and inspect it closely -- as soon as we look, we start seeing
things we don’t quite know. Seeing our own experience, we don’t quite know what
is going on.
#+end_text

:TOPICS:
- ocean
- no labels
- we create the world and become something
:END:

#+begin_text
This is like watching the ocean. Do you remember what happens in the mind when
watching the ocean? Thinking cannot fix the ocean, so it gives up and stops.
Thinking cannot freeze the waves, and say 'this wave is like this, that wave is
like that'. By the time we think that, everything has changed.

The ocean is moving. The waves are coming in, the waves are going out. The
analytical mind gives up. It gives up, lets go, and allows the open attention to
receive the whole picture at once.

With this attention we turn towards our experience. Receiving the whole picture
at once, not deciding what is going to happen, let it suprise us.

Feelings are arising. Emotions come and go. Sense of certainty and doubt
alternate like waves moving in and going out. 'What should I do? Maybe this is
good. Maybe this is not good.' This comes and goes. The heart has space for it,
and that space remains empty.

Feelings of hot and cold, pressure, the movement of the air and the ribcage.
This the experience from the inside. We have very little control over it.
Breathing in, just experience. Breathing out, just experience. There is nothing
we can fix, nothing we can change about it.

There don't have to be names and labels. The mind recognizes itself and knows
how to stay with that relaxed, wholesome attention, with the coolness of being
free to just watch.

Not understanding our experience, we make decisions about it. We decide
something is good, something is bad. At that point we create the world and we
have to become something. This we can watch, that we are creating that.
#+end_text

- feelings don't have a clear edge
- ocean stops the mind
- can't judge the waves

#+begin_text
It is not necessary to have a clear verbal theory which we produce. Feelings are
ambiguous. They don't have a clear edge. Thinking is not always certain, not
determined, and always changes.

When watching the ocean, the mind opens out, thinking stops. Nothing is certain.
Everything is changing.

We are interested in that, that we are not certain. We want to see what's there,
not only to recall a piece of knowledge from memory. Knowledge is fixed and
dead, it doesn't respond. The present is moving, the knowing attention is alive.

The ocean is not something that you can judge, 'the waves should be like this,
the waves should be like that'. It is always moving, you can't fix it. So the
mind stops the judgement. Stops the analytical process and just watches. This is
the open awareness which allows the meditation to stay with a sense of knowing,
which doesn't have fixed rigidity of judgement.

Breathing in, breathing out, it moves in its own way. There isn't a lot of
precise control that we have over it.
#+end_text

:TOPICS:
- contact
- feelings coming, going
- no choice, already moving
- endurance
- kindness
:END:

#+begin_text
When the senses make contact with the world, the feeling is born. When that
contact ceases, the feeling ceases.

Feeling, thoughts, emotions are coming in, going out. We didn't create them,
we were not the ones in control of creating it. So feeling that somehow this is
mine, doesn't seem to be according to reality.

It would be not correct to say that we created it. It would be not correct to
say that we can control how it behaves. We had no choice, it was already moving
by the time we were conscious of it.

We have to remember endurance and patience. Emotions have their energy of
movement, if they had the condition to appear, we can't stop them. If we get
involved, we will be swept away. If we step back and watch, they will move on.

Sometimes our emotions are like a screaming child. Telling them to stop is
useless, walking away and rejecting them is cruel. A child can't grow up without
kindness, we can't grow up without being kind to ourselves. Kindness can stay
with the unpleasant without rejecting it, while compassion creates structures
which allow beings to suffer less. We contain our actions with the moral
precepts and create a safe space for ourselves to be, this way we don't create
suffering for others and ourselves.

We can open the mind and have the courage to give emotions a safe space in the
heart, allow them to stay as long as they need. Remember that this is happening
in a wider context. It is one picture, not beautiful, not ugly, it is both
things. It is not easy, not difficult, it is part of the areas of experience.

The open attention can recognize that judgement, in the sense that it should be
different, that kind of judgement is out of place. The attention which can see
the body as nature, doesn't want to create a judgement, it is just like this.

Like the waves of the ocean. If someone wants to create judgement of the waves,
they are going to have a difficult time.
#+end_text
