#+TITLE: Too Much

* Too Much (1055w)

:TOPICS:
- what is real will hurt
- awareness break compulsions
- meditation is medicine
- hindrances
:END:

We sit down to meditate and turn attention inwards. What is the first thing that
we are aware of? We want something, or upset with somebody, or feeling dull and
sleepy, or trying to figure out what to do and why. Other people seem to be
sitting peacefully. How can they meditate at all?

We meditate because we want to see, and often what we see is that we better tidy
up our mind because there is no space to even sit down in there.

We often find that what we have to learn is something we never noticed before.
Something we have been doing for a long time, and only now we start to see it.

The meditation object show us where our mind is. A quiet room with nothing to do
seems like the perfect place to spend on hour thinking about our some drama or
playing out dreams and fantasies, but when the bell rings, do we feel it was
worthwhile?

Rather, we feel a bit groggy and disoriented, like waking up from a dream, and
now we have something else in our schedule. Remembering the value of the time to
meditate lets us keep returning to the meditation object. Remember there was a
reason, some sense of lack or suffering why you wanted to meditate.

We know that we are touching something real when it hurts. We have the courage
when we look, to develop a welcoming attitude toward difficult feelings, "Oh
great, I can finally see something! Finally getting to the bottom of this old
thing. It's not pretty but finally I know."

When we experience this, everything is going according to plan. They were caused
by our actions in the past, this is the result, and we are doing the best
possible thing by becoming aware of them.

The power of awareness is to break compulsions. When we can't see, the mind runs
itself in the old program and we only notice when the results are painful. When
we see it, then we have the freedom to stop.

Trying to find out who, what and when, is fruitless. Ruminating on the drama
only pulls on the hooks and they dig in deeper. These questions don't have a way
out. This is not the direction how to contemplate.

Then we look for the right recipe. "What meditation technique should I practice?
How can I reach a deeper level? There must be a teacher who can tell me what to
do." We can recognize these thoughts, and know that we are in doubt. Stepping
back and knowing the mind is experiencing doubt.

And sometimes there is something we know we have to do. Asking for forgiveness
if we made a mistake, or forgiving a mistake and moving on. Acknowledging a
situation and resolving the built-up tension in a patient, skilful manner.

Trusting the truth means the trust in cause and effect, that there is an order,
a natural law according to which things play out, a truth which we didn't create
but we can recognize and trust. Skilful actions result in the best possible
outcome, even when that means confronting what is difficult, knowing that
avoiding that difficulty will only let it continue longer and create more pain.

But when it comes to the hindrances and defilements of the heart and mind, we
are often simply getting in the way with our restlessness to do something.

Awareness breaks compulsions, patient endurance lets the fire burn itself out.
Often there is nothing to do. The results are felt, but that is not in our
control.

The simple practice of waiting for the fire to burn down is powerful. "Should I
say something? This time I really should tell them. I know I am right." We would
rather like some action and drama, but that jumpiness created the fire in the
first place.

Our intelligence is limited when we are excited or upset. If we can't wait, if
we are so compelled and driven that this can't wait until we cool down, then
what good can expect to come of it? Maybe we can't think of anything good but we
can remember to wait until we see better.

If we can wait, that often solves half the problem already, which was us. Maybe
there will be something to do, but often there won't be, because the problem was
entirely in our excitement or upset.

It makes a difference what we trust and what we believe, even when we haven't
yet confirmed it and can can't say for sure.

A sense of trust in the teachings and the good-will of others is essential.

The Buddha said his teachings are only about two things: suffering and the end
of suffering. He had given his teachings motivated by compassion, because he
believed this was going to help those who wish to understand.

He teaches that results appear from a cause, not without a cause. If there is a
cause for something to be there, it will be there. If there isn't a cause for it
to be there, it will not be there.

Whatever happens, if it is not in our control, it happened through causes, and
this was either a necessary outcome in some way, or we caused it to ourselves in
the past, but trust that with patience or skilful actions it will work out in
the best possible way, and this is the best thing which we can be experiencing
now.

The part which is ours, we can take care of. The rest will work out in whatever
way it must. We don't have to create a solution, that is not up to us.

This rests on the foundation of virtue, a wholesome environment and a trust in
truth. We examine our conduct, abandon unwholesome habits and develop wholesome
ones. We examine our environment, avoid the company of malicious people and
cultivate the company of virtuous people. This create a safe environment to live
and for going through difficulties.

Ask yourself, "Can I find the space in my heart to be with this, as long as it
needs to be here?" You probably can, but you have to ask the question.

