[[introduction-en]]
= Introduction

While I was studying at Budapest in 2005, I remember looking for books
which could help me get a useful perspective on my confused experiences.
There was no lack of explanation and advice, but they were missing a
concrete direction: ‘Interesting ideas, but what do I _do_ and how?’ I
believe that good instruction should enable one to do more than before,
shed light on the ‘what’ and ‘how’, and even on the ‘why’.

The first book which gave me a tangible foothold was Ajahn Sumedho’s
short book, _The Four Noble
Truths_.footnote:[https://forestsangha.org/teachings/books/the-four-noble-truths?language=English[The
Four Noble Truths (forestsangha.org)]] It provided an introduction to a
practical method of investigation with examples of Ajahn Sumedho’s own
struggles. Later, when I was staying at Amaravati Buddhist Monastery in
England, I read his other book __Mindfulness: the Path to the
Deathless__footnote:[https://forestsangha.org/teachings/books/mindfulness-the-path-to-the-deathless?language=English[Mindfulness:
The Path to the Deathless (forestsangha.org)]] and found it illuminating
as well.

I mention these books here because certain topics are covered in more
detail there, and if you are reading this book, they might also be
helpful.

Here, I collect advice and teachings that I wish I had read, or someone
had told me sooner, during the years since those early books. The right
answer remains obscured until we learn how to ask the right question.

I included diagrams and illustrations, which communicate on a different
channel than words, alongside the prose text. When I start drawing a
diagram, I discover relationships between terms which I hadn’t thought
of before. When I see somebody else’s diagrams, they show me how terms
are connected on a larger scale, and I ask where that representation can
be found on the map of my experience.

Illustrations of the meditation postures were carefully drawn by
Madalena Scafuro.

The Venerable Bhikkhu Kovilo carried out a large amount of editing work
on the text and converted my Hungarian-flavoured English into native
idioms and fluid phrases. I am grateful that they have dedicated their
time and energy to the project and this guide is all the better for it.
In regards to any part of this book which seem disorienting, unclear or
confusing, the responsibility and fault remain with me. Leave those
parts behind and return to learning from the Buddha, our incomparable
teacher. He taught the timeless truth, the complete ending of suffering,
because he had faith in our ability to recognize it.

Over the years, I have received much help and support from my first
teachers, who are my parents, and from monastic teachers and friends. We
may feel inadequate and not believe that we can ever feel happy, but our
teachers believe in us and wish us to succeed, to overcome confusion and
flourish in our life. I offer these words in this spirit.

Gambhīro Bhikkhu +
2021 November, +
Sumedhārāma Buddhist Monastery, Portugal
