[[mn2-sabbasava-hu]]
= Az Összes Káros Folyamatról (részlet)

_https://a-buddha-ujja.hu/mn-2/hu/forizs-laszlo[MN 2], Sabbāsava Sutta_

_(A káros folyamatok megszüntetése az alapos figyelmen alapszik)_

Bizony mondom, szerzetesek, a káros folyamatok megszüntetése csak azok
számára lehetséges, akikben megvan a tudás és látnak; akikben viszont
nincs meg a tudás és nem látnak, azoknak nem lehetséges. Mit kell tudni
és látni, szerzetesek, a káros folyamatok megszüntetéséhez? Ez az
alapos, mindenen keresztüllátó elme és a nem alapos, nem mindenen
keresztüllátó elme különbsége. Amikor a szerzetes nem elmélkedik elég
alaposan, új káros folyamatok keletkeznek, a már létrejöttek pedig
felerősödnek. Amikor a szerzetes alaposan elmélkedik, nem keletkeznek új
káros folyamatok, a már létrejöttek pedig eltűnnek.

_(Aki nem ismeri a Tant, a nézetek sűrű bozótjába gabalyodik)_

Nem elég alaposan így elmélkedik:

‘Léteztem én a múltban? Nem léteztem a múltban?’

‘Mi voltam a múltban? Hogy léteztem a múltban? Abból, ami voltam, mivé
lettem a múltban?’

‘Létezni fogok a jövőben? Nem fogok létezni a jövőben?’

‘Mi leszek a jövőben? Hogy fogok létezni a jövőben? Abból, ami voltam,
mivé leszek a jövőben?’

Vagy most, a jelenben, kételyekkel a bensejében:

‘Létezem én? Vagy nem létezem? Mi vagyok? Hogyan létezem? Honnan jött e
lény? És hová tart?’

Mivel ezeket nem fontolja meg alaposan, e hat nézet valamelyike alakul
ki benne:

‘Van átmanom’footnote:[átman: ‘önmaga’, az (ami mindig) önmaga (marad).]
– úgy alakul ki benne ez a nézet, mintha igaz és megalapozott lenne.

Vagy: ‘Nincs átmanom’ … +
‘Az átmannal fogom fel az átmant’ … +
‘Az átmannal fogom fel a nem-átmant’ … +
‘A nem-átmannal fogom fel az átmant’ … +
‘Ez az átmanom, ami beszél és érez, ami mindenütt megtapasztalja a jó és
a rossz tettek gyümölcsét – nos, ez az átmanom állandó, stabil,
örökkétartó, nincs alávetve a szüntelen átalakulásnak, örökké ugyanaz
marad’.

Ezt nevezik, szerzetesek, a nézetekbe gabalyodásnak, a nézetek sűrű
bozótjának, a nézetek erdejének, a nézetek zavarának, a nézetek
kínlódásának, a nézetek béklyójának. A nézetek béklyóival megkötözött,
tanításban nem részesült, evilági ember nem szabadul meg a születéstől,
öregedéstől és haláltól, a bánattól, a jajveszékeléstől, a fájdalomtól,
a csüggedéstől és a kétségbeeséstől. Bizony mondom, nem szabadul meg a
szenvedéstől.

_(A nemes szívű tanítvány bölcsen elmélkedik)_

Bölcsen így elmélkedik: +
‘Ez a szenvedés’; +
‘Ez a szenvedés keletkezése’; +
‘Ez a szenvedés megszűnése’; +
‘Ez a szenvedés megszűnéséhez vezető út’.

Amikor bölcsen így elmélkedik, a három béklyó – az önvaló nézete, a
kétely és a vallási szertartásokhoz ragaszkodás – megszűnik benne.

_(Konklúzió)_

Szerzetesek, arról a szerzetesről, aki belátással … megfékezéssel …
használattal … béketűréssel … elkerüléssel … eltávolítással …
gyakorlással, megszabadult a káros folyamatoktól, – arról a szerzetesről
mondják, szerzetesek, hogy megszabadult az összes káros folyamattól,
megszüntette a sóvárgást, kioldozta a ragaszkodás béklyóit, és
tökéletesen átlátva az önteltségen véget vetett a szenvedésnek.

_(ford. Fórizs László)_
